// ==============================================================================
// WORKSPACE PERSISTENCE (IndexedDB — Native)
// ==============================================================================
// Unified IndexedDB layer for the entire tools domain.
//
// This file merges two previously separate concerns:
//   - tools-db.ts  (tool result history: blobs, metadata)
//   - workspaceDB.ts (design-lab workspace persistence: canvas state)
//
// Uses native browser IndexedDB only — no external packages required.
// Gracefully degrades in private/incognito mode or when storage is blocked.
// ==============================================================================

// ── Tool Results DB ─────────────────────────────────────────────────────────

export interface ToolResult {
  id: string;       // UUID generated by crypto.randomUUID()
  toolName: string; // matches the tool slug in tool-registry.ts
  blob?: Blob;      // output image file (never store sensitive user data here)
  metadata?: Record<string, unknown>;
  timestamp: number;
}

const TOOLS_DB_NAME = 'designlab_tools_db';
const TOOLS_DB_VERSION = 1;
const TOOLS_STORE = 'results';

let toolsDbInstance: IDBDatabase | null = null;
let toolsDbPromise: Promise<IDBDatabase | null> | null = null;

export function initToolsDB(): Promise<IDBDatabase | null> {
  if (typeof window === 'undefined') return Promise.resolve(null);

  if (toolsDbPromise) return toolsDbPromise;

  toolsDbPromise = new Promise((resolve) => {
    try {
      const request = indexedDB.open(TOOLS_DB_NAME, TOOLS_DB_VERSION);

      request.onerror = () => {
        console.warn('[WorkspaceDB] Tool results DB init failed (private mode?)', request.error);
        resolve(null);
      };

      request.onsuccess = () => {
        toolsDbInstance = request.result;
        resolve(request.result);
      };

      request.onupgradeneeded = (event) => {
        const db = (event.target as IDBOpenDBRequest).result;
        if (!db.objectStoreNames.contains(TOOLS_STORE)) {
          const store = db.createObjectStore(TOOLS_STORE, { keyPath: 'id' });
          store.createIndex('by-tool', 'toolName', { unique: false });
          store.createIndex('by-timestamp', 'timestamp', { unique: false });
        }
      };
    } catch (err) {
      console.warn('[WorkspaceDB] IndexedDB unavailable:', err);
      resolve(null);
    }
  });

  return toolsDbPromise;
}

/** @deprecated Use initToolsDB(). Kept for backwards compat during migration. */
export const initDB = initToolsDB;

export async function saveResult(
  toolName: string,
  blob?: Blob,
  metadata?: Record<string, unknown>
): Promise<string | null> {
  const db = await initToolsDB();
  if (!db) return null;

  const id = crypto.randomUUID();
  const entry: ToolResult = { id, toolName, blob, metadata, timestamp: Date.now() };

  return new Promise((resolve) => {
    try {
      const tx = db.transaction(TOOLS_STORE, 'readwrite');
      const req = tx.objectStore(TOOLS_STORE).put(entry);
      req.onsuccess = () => resolve(id);
      req.onerror = () => { console.error('[WorkspaceDB] saveResult failed:', req.error); resolve(null); };
    } catch (err) {
      console.error('[WorkspaceDB] saveResult error:', err);
      resolve(null);
    }
  });
}

export async function getResultsByTool(toolName: string): Promise<ToolResult[]> {
  const db = await initToolsDB();
  if (!db) return [];

  return new Promise((resolve) => {
    try {
      const tx = db.transaction(TOOLS_STORE, 'readonly');
      const index = tx.objectStore(TOOLS_STORE).index('by-tool');
      const req = index.getAll(toolName);
      req.onsuccess = () => {
        const results = (req.result as ToolResult[]).sort((a, b) => b.timestamp - a.timestamp);
        resolve(results);
      };
      req.onerror = () => { console.error('[WorkspaceDB] getResultsByTool failed:', req.error); resolve([]); };
    } catch (err) {
      console.error('[WorkspaceDB] getResultsByTool error:', err);
      resolve([]);
    }
  });
}

export async function getAllResults(): Promise<ToolResult[]> {
  const db = await initToolsDB();
  if (!db) return [];

  return new Promise((resolve) => {
    try {
      const tx = db.transaction(TOOLS_STORE, 'readonly');
      const req = tx.objectStore(TOOLS_STORE).getAll();
      req.onsuccess = () => {
        const results = (req.result as ToolResult[]).sort((a, b) => b.timestamp - a.timestamp);
        resolve(results);
      };
      req.onerror = () => { console.error('[WorkspaceDB] getAllResults failed:', req.error); resolve([]); };
    } catch (err) {
      console.error('[WorkspaceDB] getAllResults error:', err);
      resolve([]);
    }
  });
}

export async function deleteResult(id: string): Promise<boolean> {
  const db = await initToolsDB();
  if (!db) return false;

  return new Promise((resolve) => {
    try {
      const tx = db.transaction(TOOLS_STORE, 'readwrite');
      const req = tx.objectStore(TOOLS_STORE).delete(id);
      req.onsuccess = () => resolve(true);
      req.onerror = () => { console.error('[WorkspaceDB] deleteResult failed:', req.error); resolve(false); };
    } catch (err) {
      console.error('[WorkspaceDB] deleteResult error:', err);
      resolve(false);
    }
  });
}

export async function clearAllResults(): Promise<boolean> {
  const db = await initToolsDB();
  if (!db) return false;

  return new Promise((resolve) => {
    try {
      const tx = db.transaction(TOOLS_STORE, 'readwrite');
      const req = tx.objectStore(TOOLS_STORE).clear();
      req.onsuccess = () => resolve(true);
      req.onerror = () => { console.error('[WorkspaceDB] clearAllResults failed:', req.error); resolve(false); };
    } catch (err) {
      console.error('[WorkspaceDB] clearAllResults error:', err);
      resolve(false);
    }
  });
}

// ── Workspace (Canvas State) DB ────────────────────────────────────────────
// Used by Design Lab and Inpaint to persist canvas state across sessions.

const WORKSPACE_DB_NAME = 'designlab-designer-hub';
const WORKSPACE_DB_VERSION = 1;
const WORKSPACE_STORE_NAME = 'workspace';

let isWorkspaceDBDisabled = false;

function openWorkspaceDB(): Promise<IDBDatabase> {
  return new Promise((resolve, reject) => {
    if (isWorkspaceDBDisabled) return reject(new Error('Workspace IndexedDB is disabled for this session.'));

    try {
      const request = indexedDB.open(WORKSPACE_DB_NAME, WORKSPACE_DB_VERSION);

      request.onerror = () => {
        console.warn('[WorkspaceDB] Failed to open canvas DB. Falling back to memory-only state.', request.error);
        isWorkspaceDBDisabled = true;
        reject(request.error);
      };

      request.onsuccess = () => resolve(request.result);

      request.onupgradeneeded = (event) => {
        const db = (event.target as IDBOpenDBRequest).result;
        if (!db.objectStoreNames.contains(WORKSPACE_STORE_NAME)) {
          db.createObjectStore(WORKSPACE_STORE_NAME);
        }
      };
    } catch (err) {
      console.warn('[WorkspaceDB] Canvas DB access denied or unavailable.', err);
      isWorkspaceDBDisabled = true;
      reject(err);
    }
  });
}

export async function setItem<T>(key: string, value: T): Promise<void> {
  if (isWorkspaceDBDisabled) return;
  try {
    const db = await openWorkspaceDB();
    return new Promise((resolve, reject) => {
      const tx = db.transaction(WORKSPACE_STORE_NAME, 'readwrite');
      const req = tx.objectStore(WORKSPACE_STORE_NAME).put(value, key);
      req.onsuccess = () => resolve();
      req.onerror = () => {
        if (req.error?.name === 'QuotaExceededError') {
          console.error('[WorkspaceDB] Storage quota exceeded.');
        }
        reject(req.error);
      };
    });
  } catch (error) {
    // Fail silently — never crash UI due to storage unavailability
    console.debug('[WorkspaceDB] setItem failed:', error);
  }
}

export async function getItem<T>(key: string): Promise<T | null> {
  if (isWorkspaceDBDisabled) return null;
  try {
    const db = await openWorkspaceDB();
    return new Promise((resolve, reject) => {
      const tx = db.transaction(WORKSPACE_STORE_NAME, 'readonly');
      const req = tx.objectStore(WORKSPACE_STORE_NAME).get(key);
      req.onsuccess = () => resolve((req.result as T) ?? null);
      req.onerror = () => reject(req.error);
    });
  } catch (error) {
    console.debug('[WorkspaceDB] getItem failed:', error);
    return null;
  }
}

export async function removeItem(key: string): Promise<void> {
  if (isWorkspaceDBDisabled) return;
  try {
    const db = await openWorkspaceDB();
    return new Promise((resolve, reject) => {
      const tx = db.transaction(WORKSPACE_STORE_NAME, 'readwrite');
      const req = tx.objectStore(WORKSPACE_STORE_NAME).delete(key);
      req.onsuccess = () => resolve();
      req.onerror = () => reject(req.error);
    });
  } catch (error) {
    console.debug('[WorkspaceDB] removeItem failed:', error);
  }
}

export async function clearAll(): Promise<void> {
  if (isWorkspaceDBDisabled) return;
  try {
    const db = await openWorkspaceDB();
    return new Promise((resolve, reject) => {
      const tx = db.transaction(WORKSPACE_STORE_NAME, 'readwrite');
      const req = tx.objectStore(WORKSPACE_STORE_NAME).clear();
      req.onsuccess = () => resolve();
      req.onerror = () => reject(req.error);
    });
  } catch (error) {
    console.debug('[WorkspaceDB] clearAll failed:', error);
  }
}
